import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";

export const MUIStyle = {
  BlogItemMain: {
    // maxWidth: "480px",
    // minHeight: "550px",
    padding: {
      xs: "16px",
      sm: "16px",
      md: "16px",
      lg: "16px",
      xl: "16px",
    },
    background: commonColor.white10,
    borderRadius: "16px",
    backdropFilter: "blur(20px)",
  },
  BlogImgItem: {
    width: "100%",
    height: {
      xs: "100px",
      sm: "150px",
      md: "150px",
      lg: "150px",
      xl: "230px",
    },
    borderRadius: "24px",
    overflow: "hidden",
    "& img": {
      width: "100%",
      height: "100%",
      objectFit: "cover",
    },
  },
  BlogContent: {
    paddingTop: {
      xs: "16px",
      sm: "16px",
      md: "16px",
      lg: "20px",
      xl: "40px",
    },
    display: "flex",
    flexDirection: "column",
    height: {
      xs: "calc(100% - 100px)",
      sm: "calc(100% - 150px)",
      md: "calc(100% - 150px)",
      lg: "calc(100% - 150px)",
      xl: "calc(100% - 230px)",
    },
    justifyContent: "space-between",
  },
  BlogTitle: {
    fontSize: {
      xs: FONT_SIZE.text22,
      sm: FONT_SIZE.text22,
      md: FONT_SIZE.heading24,
      lg: FONT_SIZE.heading24,
      xl: FONT_SIZE.heading28,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.white,
  },
  BlogDesc: {
    fontSize: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text18,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey3,
    margin: {
      xs: "8px 0",
      sm: "8px 0",
      md: "8px 0",
      lg: "10px 0 20px",
      xl: "20px 0 30px",
    },
  },
  CustomBtn: {
    width: "fit-content",
    background: commonColor.green,
    border: "2px solid",
    borderColor: commonColor.green,
    boxShadow: "none",
    padding: {
      xs: "8px 16px",
      sm: "8px 16px",
      md: "12px 24px",
      lg: "12px 24px",
      xl: "12px 24px",
    },
    borderRadius: "100px",
    textTransform: "capitalize",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    transition: "all 0.3s ease-in-out",
    fontSize: {
      xs: FONT_SIZE.text16,
      sm: FONT_SIZE.text16,
      md: FONT_SIZE.text16,
      lg: FONT_SIZE.text18,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.black,
    "&:hover": {
      background: commonColor.trans,
      boxShadow: "none",
      color: commonColor.green,
    },
    "& span": {
      fontSize: FONT_SIZE.heading24,
      lineHeight: FONT_SIZE.heading24,
      transition: "all 0.3s ease-in-out",
    },
    "&:hover span": {
      color: commonColor.green,
    },
  },

};
