import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";

export const MUIStyle = {
  TabBarSec: {
    background: commonColor.white,
    position: "relative",
    width: "100%",
    padding: {
      xs: "100px 0",
      sm: "100px 0",
      md: "100px 0",
      lg: "175px 0",
      xl: "175px 0",
    },
    position: "relative",
  },
  AboutSecOuterBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    gap: "20px",
    padding: "0",
    position: "relative",
    paddingTop: "30px",
    paddingBottom: {
      xs: "100px",
      sm: "100px",
      md: "168px",
      lg: "168px",
      xl: "168px",
    },
  },
  AboutSecHeadingBox: {
    width: {
      xs: "100%",
      sm: "60%",
      md: "60%",
      lg: "60%",
      xl: "60%",
    },
  },
  AboutSecText: {
    color: commonColor.grey,
    fontSize: FONT_SIZE.text18,
    fontWeight: FONT_WEIGHT.MEDIUM,
    lineHeight: FONT_SIZE.heading28,
    textAlign: "center",
    marginBottom: "24px",
  },
  AboutSecHeading: {
    color: commonColor.black,
    fontSize: FONT_SIZE.heading32,
    lineHeight: FONT_SIZE.heading40,
    fontWeight: FONT_WEIGHT.REGULAR,
    textTransform: "uppercase",
    textAlign: "center",
  },
  TabBarSecImageBox: {
    width: "100%",
    position: "relative",
  },
  TabBarSecImage: {
    width: "100%",
  },
  TabBarSecInnerBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    gap: "20px",
    padding: "0",
    position: "relative",
  },
  TabBarSecButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: {
      xs: "stretch",
      sm: "stretch",
      md: "stretch",
      lg: "center",
      xl: "center",
    },
    flexDirection: "column",
    position: "relative",
    minHeight: "64px",
  },
  TabBarSecButtonHead: {
    background: commonColor.black5,
    width: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "350px",
      xl: "420px",
    },
    minHeight: "64px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    color: commonColor.black,
    fontSize: FONT_SIZE.heading24,
    lineHeight: FONT_SIZE.heading32,
    fontWeight: FONT_WEIGHT.MEDIUM,
    padding: "12px 24px",
    borderRadius: "32px",
    cursor: "pointer",
    textAlign: "center",

  },
  TabBarSecButtonBody: {
    background: commonColor.greenFade3,
    width: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "100%",
      xl: "556px",
    },
    minHeight: 0,
    height: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 0,
    borderRadius: "32px",
    textAlign: "center",
    boxShadow: "0px 0px 32px rgba(0, 0, 0, 0.12)",
    overflow: "hidden",
  },
  TabBarSecButtonBodyTop: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  TabBarSecButtonBodyTopHeading: {
    color: commonColor.black,
    fontSize: FONT_SIZE.heading32,
    lineHeight: FONT_SIZE.heading40,
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    textAlign: "center",
  },
  TabBarSecButtonBodyTopText: {
    color: commonColor.grey,
    fontSize: FONT_SIZE.text18,
    lineHeight: FONT_SIZE.heading26,
    fontWeight: FONT_WEIGHT.REGULAR,
    display: "block",
    textAlign: "center",
    paddingTop: "10px",
  },
  TabBarSecButtonBodyText: {
    color: commonColor.grey,
    fontSize: FONT_SIZE.text18,
    lineHeight: FONT_SIZE.heading32,
    fontWeight: FONT_WEIGHT.REGULAR,
    textAlign: "center",
    paddingTop: "10px",
  },
  TabBarSecMyRow: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: {
      xs: "column",
      sm: "column",
      md: "row",
      lg: "row",
      xl: "row",
    },
    gap: "20px",
  },
  TabBarSecMyColLeft: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    gap: "20px",
    width: {
      xs: "100%",
      sm: "100%",
      md: "60%",
      lg: "60%",
      xl: "70%",
    },
  },
  TabBarSecMyColRight: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    gap: "20px",
    width: {
      xs: "100%",
      sm: "100%",
      md: "40%",
      lg: "40%",
      xl: "30%",
    },
  },

  TestImage: {
    width: {
      xs: "100%",
      sm: "100%",
      md: "504px",
      lg: "504px",
      xl: "504px",
    },
    height: {
      xs: "auto",
      sm: "auto",
      md: "560px",
      lg: "560px",
      xl: "560px",
    },
    objectFit: "cover",
    borderRadius: "32px",
    filter: 'drop-shadow(4px 5px 32px rgba(0, 0, 0, 0.3))'
  },
  BannerSVGContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
  }
};
