import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";

export const MUIStyle = {
  TabBarSec: {
    // background: commonColor.white,
    position: "relative",
    width: "100%",
    padding: {
      xs: "30px 0",
      sm: "30px 0",
      md: "30px 0",
      lg: "30px 0",
      xl: "30px 0",
    },
    position: "relative",
    minHeight: "100vh",
    backgroundColor: '#030712'
  },
  AboutSecOuterBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    gap: "20px",
    padding: "0",
    position: "relative",
    paddingBottom: {
      xs: "10px",
      sm: "10px",
      md: "15px",
      lg: "15px",
      xl: "20px",
    },
  },
  AboutSecHeadingBox: {
    width: {
      xs: "100%",
      sm: "60%",
      md: "60%",
      lg: "60%",
      xl: "60%",
    },
  },
  AboutSecText: {
    color: commonColor.grey,
    fontSize: {
      xs: FONT_SIZE.text12,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text16,
      lg: FONT_SIZE.text16,
      xl: FONT_SIZE.text18,
    },
    fontWeight: FONT_WEIGHT.MEDIUM,
    lineHeight: FONT_SIZE.heading28,
    textAlign: "center",
    marginBottom: {
      xs: "10px",
      sm: "10px",
      md: "10px",
      lg: "10px",
      xl: "20px",
    },
  },
  AboutSecHeading: {
    // color: commonColor.black,
    fontSize: {
      xs: FONT_SIZE.text20,
      sm: FONT_SIZE.text22,
      md: FONT_SIZE.heading24,
      lg: FONT_SIZE.heading24,
      xl: FONT_SIZE.heading28,
    },
    lineHeight: FONT_SIZE.heading40,
    fontWeight: FONT_WEIGHT.REGULAR,
    textTransform: "uppercase",
    textAlign: "center",
  },
  TabBarSecImageBox: {
    width: "100%",
    position: "relative",
  },
  TabBarSecImage: {
    width: "100%",
  },
  TabBarSecInnerBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    gap: {
      xs: "10px",
      sm: "10px",
      md: "10px",
      lg: "10px",
      xl: "20px",
    },
    padding: "0",
    position: "relative",
  },
  TabBarSecButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: {
      xs: "stretch",
      sm: "stretch",
      md: "stretch",
      lg: "center",
      xl: "center",
    },
    flexDirection: "column",
    position: "relative",
    // minHeight: "64px",
    width: {
      xs: "100%",
      sm: "100%",
    }
  },
  TabBarSecButtonHead: {
    // background: commonColor.black5,
    width: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "300px",
      xl: "300px",
    },
    // minHeight: "64px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // color: commonColor.black,
    fontSize: {
      xs: FONT_SIZE.text16,
      sm: FONT_SIZE.text16,
      md: FONT_SIZE.text16,
      lg: FONT_SIZE.text16,
      xl: FONT_SIZE.text18,
    },
    lineHeight: {
      xs: FONT_SIZE.text18,
      sm: FONT_SIZE.text18,
      md: FONT_SIZE.text18,
      lg: FONT_SIZE.text18,
      xl: FONT_SIZE.text20,
    },
    fontWeight: FONT_WEIGHT.MEDIUM,
    padding: {
      xs: "8px 12px",
      sm: "8px 12px",
      md: "8px 12px",
      lg: "8px 12px",
      xl: "10px 14px",
    },
    borderRadius: "32px",
    cursor: "default",
    textAlign: "center",

  },
  TabBarSecButtonBody: {
    background: commonColor.greenFade3,
    width: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "100%",
      xl: "100%",
    },
    minHeight: 0,
    height: 0,
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-evenly",
    alignItems: "center",
    padding: 0,
    borderRadius: "32px",
    textAlign: "center",
    boxShadow: "0px 0px 32px rgba(0, 0, 0, 0.12)",
    overflow: "hidden",
    position: "relative",
  },
  TabBarSecButtonBodyTop: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  TabBarSecButtonBodyTopHeading: {
    color: commonColor.black,
    fontSize: {
      xs: FONT_SIZE.text16,
      sm: FONT_SIZE.text16,
      md: FONT_SIZE.text16,
      lg: FONT_SIZE.text16,
      xl: FONT_SIZE.text18,
    },
    lineHeight: {
      xs: FONT_SIZE.text16,
      sm: FONT_SIZE.text16,
      md: FONT_SIZE.text16,
      lg: FONT_SIZE.text16,
      xl: FONT_SIZE.text18,
    },
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    textAlign: "center",
    display: {
      xs: "none",
      sm: "none",
      md: "block",
      lg: "block",
      xl: "block",
    }
  },
  TabBarSecButtonBodyTopText: {
    color: commonColor.black,
    fontSize: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text16,
    },
    lineHeight: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text16,
    },
    fontWeight: FONT_WEIGHT.REGULAR,
    display: "block",
    textAlign: "center",
    paddingTop: "10px",
  },
  TabBarSecButtonBodyText: {
    color: commonColor.black,
    fontSize: {
      xs: FONT_SIZE.text12,
      sm: FONT_SIZE.text12,
      md: FONT_SIZE.text12,
      lg: FONT_SIZE.text12,
      xl: FONT_SIZE.text14,
    },
    lineHeight: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text16,
    },
    fontWeight: FONT_WEIGHT.REGULAR,
    textAlign: "center",
    paddingTop: "10px",
  },
  TabBarSecMyRow: {
    display: "flex",
    justifyContent: "center",
    alignItems: "flex-start",
    flexDirection: {
      xs: "column",
      sm: "column",
      md: "row",
      lg: "row",
      xl: "row",
    },
    gap: "20px",
    position: "relative",
  },
  TabBarSecMyColLeft: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    // alignSelf: 'center',
    flexDirection: "column",
    gap: "20px",
    width: {
      xs: "100%",
      sm: "100%",
      md: "50%",
      lg: "50%",
      xl: "70%",
    },
    // position: 'sticky',
    // top: '2vh'
  },
  TabBarSecMyColRight: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    gap: "20px",
    width: {
      xs: "100%",
      sm: "100%",
      md: "40%",
      lg: "40%",
      xl: "30%",
    },
  },

  TestImage: {
    width: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "100%",
      xl: "100%",
    },
    height: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "100%",
      xl: "100%",
    },
    objectFit: "cover",
    borderRadius: "8px",
    // filter: 'drop-shadow(4px 5px 32px rgba(0, 0, 0, 0.3))',
  },
  BannerSVGContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
  }
};
