import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";
import { light } from "@mui/material/styles/createPalette";

export const MUIStyle = {
  PricingQuoteSec: {
    width: "100%",
    padding: {
      xs: "50px 0",
      sm: "50px 0",
      md: "50px 0",
      lg: "50px 0",
      xl: "100px 0",
    },
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },

  PricingQuoteHeadingBoxOuter: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  PricingQuoteHeadingBoxInner: {
    maxWidth: {
      xs: "100%",
      sm: "100%",
      md: "40%",
      lg: "25%",
      xl: "25%",
    },
    marginBottom: {
      xs: "20px",
      sm: "20px",
      md: "48px",
      lg: "48px",
      xl: "48px",
    },
  },
  SubHeading: {
    fontSize: {
      xs: FONT_SIZE.text12,
      sm: FONT_SIZE.text12,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text16,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
    marginBottom: {
      xs: "10px",
      sm: "10px",
      md: "24px",
      lg: "15px",
      xl: "24px",
    },
  },
  Heading: {
    fontSize: {
      xs: FONT_SIZE.text20,
      sm: FONT_SIZE.text22,
      md: FONT_SIZE.heading24,
      lg: FONT_SIZE.heading24,
      xl: FONT_SIZE.heading28,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.black,
    textTransform: "uppercase",
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
    marginBottom: {
      xs: "10px",
      sm: "10px",
      md: "10px",
      lg: "10px",
      xl: "20px",
    },
  },
  Bodytext: {
    fontSize: {
      xs: FONT_SIZE.text12,
      sm: FONT_SIZE.text12,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text16,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
    marginBottom: {
      xs: "10px",
      sm: "10px",
      md: "24px",
      lg: "15px",
      xl: "24px",
    },
  },
  PricingQuoteFormGrid: {
    display: "grid",
    gridTemplateColumns: {
      xs: "1fr",
      sm: "1fr",
      md: "1fr",
      lg: "1fr 1fr",
      xl: "1fr 1fr",
    },
    gap: {
      xs: "20px",
      sm: "20px",
      md: "30px",
      lg: "30px",
      xl: "30px",
    },
    position: "relative",
  },
  PricingQuoteFormCol: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "column",
    borderRadius: "30px",
    padding: {
      xs: "20px",
      sm: "20px",
      md: "36px",
      lg: "36px",
      xl: "36px",
    },
    overflow: "hidden",
    border: `1px solid ${commonColor.grey600}`,
    boxShadow: `0px 0px 15px ${commonColor.black12}`,
    position: "relative",
    zIndex: 2,
    backgroundColor: commonColor.white,
  },
  PricingQuoteCol: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: commonColor.black,
    borderRadius: "30px",
    overflow: "hidden",
    position: "relative",
    zIndex: 2,
  },
  PricingQuoteFormImage: {
    width: "100%",
    height: {
      xs: "100%",
      sm: "100%",
      md: "100dvh",
      lg: "100dvh",
      xl: "100dvh",
    },
    maxWidth: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "100%",
      xl: "100%",
    },
    objectFit: "contain",
  },
  PricingQuoteFormOuter: {
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    // gap: "20px",
    width: "100%",
    height: "100%",
    justifyContent: "space-between",
  },
  PricingQuoteInputItem: {
    display: "flex",
    flexDirection: "column",
    gap: "5px",
    width: "100%",
    "& .MuiOutlinedInput-root": {
      borderRadius: "100px !important",
      borderColor: commonColor.grey600,
      "& fieldset": {
        borderColor: commonColor.grey600,
      },

      "&:hover fieldset": {
        borderColor: commonColor.grey600,
      },
      "&.Mui-focused fieldset": {
        borderColor: commonColor.grey600,
      },
      "&.Mui-focused": {
        borderColor: commonColor.grey600,
      },

    },
    "& .MuiInputBase-input": {
      padding: "0px 20px 5px",
      minHeight: "48px",
      backgroundColor: commonColor.white,
      color: commonColor.black,
      fontSize: FONT_SIZE.text18,
      lightHeight: "1.5em",
      fontWeight: FONT_WEIGHT.MEDIUM,
      width: "100%",
      borderColor: commonColor.grey600,
      borderRadius: "50px",
      "&::placeholder": {
        color: commonColor.grey,
        fontSize: FONT_SIZE.text16,
        fontWeight: FONT_WEIGHT.MEDIUM,
        lineHeight: "30px",
        opacity: 1,
      },
    },
    "& .MuiSelect-select": {
      display: "flex",
      alignItems: "center",

    },
  },
  PricingQuoteInputLabel: {
    fontSize: FONT_SIZE.text18,
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.black,
    textAlign: "left",
    paddingLeft: "5px",
    transition: "all 0.5s ease-in-out",
    "span": {
      color: commonColor.red,
    },
  },

  PricingQuoteInputFlex: {
    display: "grid",
    gridTemplateColumns: "90px 1fr",
    gap: "8px",
    width: "100%",
  },
  PricingQuoteInputItemRow: {
    display: "flex",
    flexDirection: {
      xs: "column",
      sm: "column",
      md: "row",
      lg: "row",
      xl: "row",
    },
    gap: "20px",
    width: "100%",
  },

  PricingQuoteInputFile: {
    padding: "12px 20px",
    height: "65px",
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: commonColor.white,
    color: commonColor.black,
    fontSize: FONT_SIZE.text18,
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.MEDIUM,
    width: "100%",
    border: `1px solid ${commonColor.grey600}`,
    borderRadius: "50px",
    overflow: "hidden",
    position: "relative",
    "& input": {
      opacity: 0,
      height: "40px",
      maxWidth: "152px",
      width: "100%",
      position: "absolute",
      top: "50%",
      left: "10px",
      transform: "translateY(-50%)",
      zIndex: 1,
      cursor: "pointer",
    },
  },
  PricingQuoteInputFileBtn: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    width: "fit-content",
    padding: "10px 20px",
    backgroundColor: commonColor.black,
    borderRadius: "50px",
    position: "absolute",
    top: "50%",
    left: "10px",
    transform: "translateY(-50%)",
  },
  PricingQuoteInputFileText: {
    fontSize: FONT_SIZE.text16,
    lineHeight: "1",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.green,
    textAlign: "left",
    transition: "all 0.5s ease-in-out",
  },

  PricingQuoteInputFileIcon: {
    width: "20px",
    height: "20px",
    color: commonColor.green,
  },
  FormShortText: {
    fontSize: FONT_SIZE.text12,
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.grey,
    textAlign: "left",
    transition: "all 0.5s ease-in-out",
  },
  PricingQuoteInputBtn: {
    background: commonColor.green,
    border: "2px solid",
    borderColor: commonColor.green,
    boxShadow: "none",
    padding: {
      xs: "15px 28px",
      sm: "15px 28px",
      md: "20px 30px",
      lg: "20px 30px",
      xl: "20px 30px",
    },
    borderRadius: "100px",
    textTransform: "capitalize",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    transition: "all 0.3s ease-in-out",
    fontSize: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text16,
      lg: FONT_SIZE.text16,
      xl: FONT_SIZE.text20,
    },
    lineHeight: "1",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.black,
    "&:hover": {
      background: commonColor.white,
      boxShadow: "none",
      color: commonColor.green,
    },
    // marginTop: {
    //   xs: "20px",
    //   sm: "20px",
    //   md: "30px",
    //   lg: "30px",
    //   xl: "30px",
    // },
  },
  PricingQuoteInputFileName: {
    fontSize: FONT_SIZE.text16,
    lineHeight: "1",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.black,
    textAlign: "left",
    transition: "all 0.5s ease-in-out",
    maxWidth: "70%",
    width: "100%",
    textOverflow: "ellipsis",
    overflow: "hidden",
    whiteSpace: "nowrap",
    display: "block",
    marginLeft: "auto",
  },
  CountryCodeText: {
    fontSize: FONT_SIZE.text16,
    lineHeight: "1",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.black,
    textAlign: "left",
    transition: "all 0.5s ease-in-out",
    marginLeft: "10px",
  },
  BannerSVGContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
  }

};
