import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";
import { BANNER1 } from "@/values/Constants/ImageConstants";
import { Backdrop } from "@mui/material";

export const MUIStyle = {
    AboutMain: {
        position: "relative",
        background: `url(${BANNER1})`,
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundRepeat: "no-repeat",
        width: "100%",
        padding: {
            xs: "50px 0",
            sm: "50px 0",
            md: "100px 0",
            lg: "132px 0",
            xl: "132px 0",
        },
        minHeight: "100vh",
        overflow: "hidden", 
    },

    AboutDashBoardImg: {
        order: {
            xs: "3",
            sm: "3",
            md: "3",
            lg: "3",
            xl: "3",
        },
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "column",
        gap: "20px",
        padding: "0",
        marginTop: {
            xs: "20px",
            sm: "20px",
            md: "50px",
            lg: "50px",
            xl: "50px",
        },
        position: "relative",
        zIndex: "1",
        "& img": {
            width: {
                xs: "90%",
                sm: "80%",
                md: "60%",
                lg: "60%",
                xl: "80%",
            },
            height: {
                xs: "90%",
                sm: "80%",
                md: "60%",
                lg: "60%",
                xl: "80%",
            },
            objectFit: "contain",
        },
    },

    AboutSecOuterBox: {
        order: {
            xs: "1",
            sm: "1",
            md: "2",
            lg: "2",
            xl: "2",
        },
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        flexDirection: "column",
        gap: "20px",
        padding: "0",
        position: "relative",
        paddingTop: "30px",
        paddingBottom: {
            xs: "10px",
            sm: "10px",
            md: "100px",
            lg: "264px",
            xl: "264px",
        }
    },
    AboutSecHeadingBox: {
        width: {
            xs: "100%",
            sm: "50%",
            md: "50%",
            lg: "50%",
            xl: "50%",
        },
    },
    AboutSecText: {
        color: commonColor.grey,
        fontSize: {
            xs: FONT_SIZE.text12,
            sm: FONT_SIZE.text14,
            md: FONT_SIZE.text16,
            lg: FONT_SIZE.text16,
            xl: FONT_SIZE.text20,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        lineHeight: FONT_SIZE.heading28,
        textAlign: "center",
        marginBottom: "24px",
    },
    AboutSecHeading: {
        color: commonColor.white,
        fontSize: {
            xs: FONT_SIZE.text20,
            sm: FONT_SIZE.text22,
            md: FONT_SIZE.heading24,
            lg: FONT_SIZE.heading24,
            xl: FONT_SIZE.heading28,
        },
        lineHeight: FONT_SIZE.heading40,
        fontWeight: FONT_WEIGHT.REGULAR,
        textTransform: "uppercase",
        textAlign: "center",
    },
    AboutAllBtns: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "10px",
            sm: "10px",
            md: "75px",
            lg: "75px",
            xl: "75px",
        },
        gridTemplateColumns: "repeat(2, 1fr)",
        gap: "20px 0",
        order: {
            xs: "2",
            sm: "2",
            md: "1",
            lg: "1",
            xl: "1",

        },
        left: "0",
        minHeight: {
            md: "400px",
            sm: "400px",
            lg: "450px",
            xl: "450px",
        },
        width: "100%",
        display: {
            xs: "none",
            sm: "none",
            md: "grid",
            lg: "grid",
            xl: "grid",
        }
    },
    Btn: {
        background: commonColor.trans,
        color: commonColor.white,
        fontSize: {
            xs: FONT_SIZE.text10,
            sm: FONT_SIZE.text14,
            md: FONT_SIZE.text14,
            lg: FONT_SIZE.text14,
            xl: FONT_SIZE.text16,
        },
        letterSpacing: "0.7px",
        fontWeight: FONT_WEIGHT.SEMI_BOLD,
        padding: "14px 16px",
        zIndex: "1",
        boxShadow: "1px 15px 40px 0px rgb(223 255 96 / 10%)",
        borderBottom: `2px solid ${commonColor.green}`,
        background: commonColor.black,
        borderRadius: "5px",
        // "&::before": {
        //     content: '""',
        //     position: "absolute",
        //     top: "0",
        //     left: "0",
        //     width: "71px",
        //     height: "100%",
        //     zIndex: "-1",
        //     borderBottom: `2px solid ${commonColor.green}`,
        //     boxShadow: "50px 1px 50px 0px rgb(223 255 96 / 19%)",
        //     background: commonColor.black,
        // },
        display: {
            xs: "block",
            sm: "block",
        },
        margin: {
            xs: "2px",
            sm: "5px",
        },
        alignContent: "center",
        textAlign: {
            xs: "center",
            sm: "center",
        }
    },

    Btn1: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: "0%",
        left: {
            xs: "0%",
            sm: "0%",
            md: "10%",
            lg: "10%",
            xl: "10%",
        },
    },
    Btn2: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: "0%",
        right: {
            xs: "0%",
            sm: "0%",
            md: "10%",
            lg: "10%",
            xl: "10%",
        },
    },
    Btn3: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "30%",
            lg: "30%",
            xl: "30%",
        },
        left: {
            xs: "0%",
            sm: "0%",
            md: "6%",
            lg: "6%",
            xl: "6%",
        },
    },
    Btn4: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "30%",
            lg: "30%",
            xl: "30%",
        },
        right: {
            xs: "0%",
            sm: "0%",
            md: "6%",
            lg: "6%",
            xl: "6%",
        },
    },
    Btn5: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "60%",
            lg: "60%",
            xl: "60%",
        },
        left: {
            xs: "0%",
            sm: "0%",
            md: "18%",
            lg: "18%",
            xl: "18%",
        },
    },
    Btn6: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "63%",
            lg: "63%",
            xl: "63%",
        },
        right: {
            xs: "0%",
            sm: "0%",
            md: "18%",
            lg: "18%",
            xl: "18%",
        },
    },
    Btn7: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "67%",
            lg: "67%",
            xl: "67%",
        },
        left: {
            xs: "0%",
            sm: "0%",
            md: "35%",
            lg: "35%",
            xl: "35%",
        },
    },
    Btn8: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "73%",
            lg: "73%",
            xl: "73%",
        },
        right: {
            xs: "0%",
            sm: "0%",
            md: "35%",
            lg: "35%",
            xl: "35%",
        },
        transform: {
            xs: "translateX(-50%)",
            sm: "translateX(-50%)",
        },
        textAlign: {
            xs: "center",
            sm: "center",
        }
    },
    Btn9: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "67%",
            lg: "67%",
            xl: "67%",
        },
        right: {
            xs: "0%",
            sm: "0%",
            md: "5%",
            lg: "5%",
            xl: "5%",
        },
    },
    Btn10: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "90%",
            lg: "90%",
            xl: "90%",
        },
        left: {
            xs: "0%",
            sm: "0%",
            md: "5%",
            lg: "5%",
            xl: "5%",
        },
    },
    Btn11: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "95%",
            lg: "95%",
            xl: "95%",
        },
        left: {
            xs: "0%",
            sm: "0%",
            md: "45%",
            lg: "45%",
            xl: "45%",
        },
        display: {
            xs: "none",
            sm: "none",
            md: "block",
        }
    },
    Btn12: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "85%",
            lg: "85%",
            xl: "85%",
        },
        right: {
            xs: "0%",
            sm: "0%",
            md: "15%",
            lg: "15%",
            xl: "15%",
        },
    },
    Btn13: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "90%",
            lg: "90%",
            xl: "90%",
        },
        left: {
            xs: "0%",
            sm: "0%",
            md: "25%",
            lg: "25%",
            xl: "25%",
        },
    },
    Btn14: {
        position: {
            xs: "relative",
            sm: "relative",
            md: "absolute",
            lg: "absolute",
            xl: "absolute",
        },
        top: {
            xs: "0%",
            sm: "0%",
            md: "100%",
            lg: "100%",
            xl: "100%",
        },
        right: {
            xs: "0%",
            sm: "0%",
            md: "30%",
            lg: "30%",
            xl: "30%",
        },
    },



};