import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";

export const MUIStyle = {
  DigitalConstructionMain: {
    width: "100%",
    padding: {
      xs: "50px 0",
      sm: "50px 0",
      md: "50px 0",
      lg: "50px 0",
      xl: "100px 0",
    },
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: commonColor.black,
    height: '100vh'
  },

  DigitalConstructionHeadingBoxOuter: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  DigitalConstructionHeadingBoxInner: {
    maxWidth: {
      xs: "100%",
      sm: "100%",
      md: "45%",
      lg: "45%",
      xl: "45%",
    },
    marginBottom: {
      xs: "30px",
      sm: "30px",
      md: "30px",
      lg: "30px",
      xl: "40px",
    },
  },
  SubHeading: {
    fontSize: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text16,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
    marginBottom: {
      xs: "10px",
      sm: "10px",
      md: "10px",
      lg: "10px",
      xl: "20px",
    },
  },
  Heading: {
    fontSize: {
      xs: FONT_SIZE.heading24,
      sm: FONT_SIZE.heading24,
      md: FONT_SIZE.heading24,
      lg: FONT_SIZE.heading24,
      xl: FONT_SIZE.heading28,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    color: commonColor.white,
    textTransform: "uppercase",
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  ProjectText: {
    fontSize: FONT_SIZE.text18,
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  DigitalColCenter: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    maxWidth: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "100%",
      xl: "100%",
    },
    "& img": {
      width: {
        xs: "100%",
        sm: "100%",
        md: "400px",
        lg: "400px",
        xl: "500px",
      },
      height: {
        xs: "100%",
        sm: "100%",
        md: "400px",
        lg: "400px",
        xl: "500px",
      },
      objectFit: "contain",
    },
  },

  DigitalColLeft: {
    display: "flex",
    justifyContent: "space-around",
    alignItems: "center",
    flexDirection: {
      xs: "column",
      sm: "column",
      md: "row",
      lg: "row",
      xl: "row",
    },
    gap: "50px",
    maxWidth: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "100%",
      xl: "100%",
    },
    marginBottom: {
      xs: "0px",
      sm: "0px",
      md: "-130px",
      lg: "-130px",
      xl: "-130px",
    },
  },
  DigitalColRight: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: {
      xs: "column",
      sm: "column",
      md: "row",
      lg: "row",
      xl: "row",
    },
    gap: "50px",
    maxWidth: {
      xs: "100%",
      sm: "100%",
      md: "100%",
      lg: "100%",
      xl: "100%",
    },
    marginTop: {
      xs: "0px",
      sm: "0px",
      md: "-150px",
      lg: "-150px",
      xl: "-150px",
    },
  },
  DigitalContentBox: {
    padding: {
      xs: "16px",
      sm: "16px",
      md: "16px",
      lg: "16px",
      xl: "16px",
    },
    maxWidth: {
      xs: "380px",
      sm: "380px",
      md: "280px",
      lg: "276px",
      xl: "276px",
    },
    borderRadius: "8px",
    display: "flex",
    gap: "16px",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    transition: "all 0.5s ease-in-out",
  },
  ContentHeading: {
    fontSize: FONT_SIZE.text20,
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    color: commonColor.black,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  ContentText: {
    fontSize: FONT_SIZE.text16,
    lineHeight: "24px",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
};
