import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";

export const MUIStyle = {
  OnsiteSectionMain: {
    width: "100%",
    padding: {
      xs: "50px 0",
      sm: "50px 0",
      md: "50px 0",
      lg: "50px 0",
      xl: "100px 0",
    },
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: commonColor.black,
    position: 'relative',
    height: '100vh',
    overflow: 'hidden',
  },

  OnsiteSectionHeadingBoxOuter: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  OnsiteSectionHeadingBoxInner: {
    maxWidth: {
      xs: "100%",
      sm: "100%",
      md: "45%",
      lg: "45%",
      xl: "45%",
    },
    marginBottom: {
      xs: "80px",
      sm: "80px",
      md: "48px",
      lg: "48px",
      xl: "48px",
    },
  },
  SubHeading: {
    fontSize: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text16,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
    marginBottom: {
      xs: "24px",
      sm: "24px",
      md: "24px",
      lg: "15px",
      xl: "24px",
    },
  },
  Heading: {
    fontSize: {
      xs: FONT_SIZE.heading24,
      sm: FONT_SIZE.heading24,
      md: FONT_SIZE.heading24,
      lg: FONT_SIZE.text20,
      xl: FONT_SIZE.heading28,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    color: commonColor.white,
    textTransform: "uppercase",
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  ProjectText: {
    fontSize: FONT_SIZE.text18,
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  Row: {
    paddingTop: {
      xs: "0",
      sm: "0",
      md: "0",
      lg: "0",
      xl: "0",
    },

    display: "flex",
    justifyContent: "center",
    // alignItems: "center",
    flexDirection: {
      xs: "column",
      sm: "column",
      md: "row",
      lg: "row",
      xl: "row",
    },
    gap: {
      xs: "50px",
      sm: "50px",
      md: "100px",
      lg: "100px",
      xl: "100px",
    },
  },
  ColLeft: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "column",
    width: {
      xs: "100%",
      sm: "100%",
      md: "50%",
      lg: "50%",
      xl: "50%",
    },
    "& img": {
      width: {
        xs: "100%",
        sm: "100%",
        md: "100%",
        lg: "50%",
        xl: "100%",
      },
      height: {
        xs: "100%",
        sm: "100%",
        md: "200px",
        lg: "200px",
        xl: "250px",
      },
      marginBottom: {
        xs: "25px",
        sm: "25px",
        md: "25px",
        lg: "25px",
        xl: "45px",
      },
      objectFit: "contain",
    },
  },

  ColRight: {
    display: "flex",
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "column",
    width: {
      xs: "100%",
      sm: "100%",
      md: "50%",
      lg: "50%",
      xl: "50%",
    },
    "& img": {
      width: {
        xs: "220px",
        sm: "220px",
        md: "220px",
        lg: "100px",
        xl: "220px",
      },
      height: {
        xs: "100%",
        sm: "100%",
        md: "440px",
        lg: "200px",
        xl: "250px",
      },
      marginBottom: {
        xs: "25px",
        sm: "25px",
        md: "25px",
        lg: "25px",
        xl: "45px",
      },
      objectFit: "contain",
    },
  },
  LEftContent: {
    padding: {
      xs: "0",
      sm: "0",
      md: "0 50px",
      lg: "0 50px",
      xl: "0 50px",
    },
  },
  ContentHeading: {
    fontSize:{
      xs: FONT_SIZE.text18,
      sm: FONT_SIZE.text18,
      md: FONT_SIZE.text18,
      lg: FONT_SIZE.text18,
      xl: FONT_SIZE.heading24,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    color: commonColor.white,
    textTransform: "uppercase",
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
    marginBottom: "24px",
  },
  ContentText: {
    fontSize: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text18,
    },
    lineHeight: "1.5em",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  VisionSVGContainer: {
    position: "absolute",
    top: "0",
    left: "0",
    width: "100%",
    height: "100%",
  }
};
