import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";

export const MUIStyle = {
  OnsiteSectionMain: {
    width: "100%",
    padding: {
      xs: "100px 0",
      sm: "100px 0",
      md: "100px 10px",
      lg: "284px 10px",
      xl: "284px 130px",
    },
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: commonColor.black,
    position: 'relative'
  },

  OnsiteSectionHeadingBoxOuter: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  OnsiteSectionHeadingBoxInner: {
    maxWidth: {
      xs: "100%",
      sm: "100%",
      md: "45%",
      lg: "45%",
      xl: "45%",
    },
    marginBottom: {
      xs: "80px",
      sm: "80px",
      md: "96px",
      lg: "96px",
      xl: "96px",
    },
  },
  SubHeading: {
    fontSize: {
      xs: FONT_SIZE.text14,
      sm: FONT_SIZE.text14,
      md: FONT_SIZE.text14,
      lg: FONT_SIZE.text14,
      xl: FONT_SIZE.text16,
    },
    lineHeight: "32px",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
    marginBottom: "24px",
  },
  Heading: {
    fontSize: {
      xs: FONT_SIZE.heading24,
      sm: FONT_SIZE.heading24,
      md: FONT_SIZE.heading24,
      lg: FONT_SIZE.heading24,
      xl: FONT_SIZE.heading28,
    },
    lineHeight: "40px",
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    color: commonColor.white,
    textTransform: "uppercase",
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  ProjectText: {
    fontSize: FONT_SIZE.text18,
    lineHeight: "32px",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  Row: {
    paddingTop: {
      xs: "0",
      sm: "0",
      md: "135px",
      lg: "135px",
      xl: "135px",
    },

    display: "flex",
    justifyContent: "center",
    // alignItems: "center",
    flexDirection: {
      xs: "column",
      sm: "column",
      md: "row",
      lg: "row",
      xl: "row",
    },
    gap: {
      xs: "50px",
      sm: "50px",
      md: "100px",
      lg: "100px",
      xl: "100px",
    },
  },
  ColLeft: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    width: {
      xs: "100%",
      sm: "100%",
      md: "70%",
      lg: "70%",
      xl: "70%",
    },
    "& img": {
      width: {
        xs: "100%",
        sm: "100%",
        md: "100%",
        lg: "100%",
        xl: "100%",
      },
      height: {
        xs: "100%",
        sm: "100%",
        md: "440px",
        lg: "440px",
        xl: "440px",
      },
      marginBottom: {
        xs: "24px",
        sm: "24px",
        md: "45px",
        lg: "45px",
        xl: "45px",
      },
      objectFit: "contain",
    },
  },

  ColRight: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    width: {
      xs: "100%",
      sm: "100%",
      md: "30%",
      lg: "30%",
      xl: "30%",
    },
    "& img": {
      width: {
        xs: "220px",
        sm: "220px",
        md: "220px",
        lg: "220px",
        xl: "220px",
      },
      height: {
        xs: "100%",
        sm: "100%",
        md: "440px",
        lg: "440px",
        xl: "440px",
      },
      marginBottom: {
        xs: "24px",
        sm: "24px",
        md: "45px",
        lg: "45px",
        xl: "45px",
      },
      objectFit: "contain",
    },
  },
  LEftContent: {
    padding: {
      xs: "0",
      sm: "0",
      md: "0 140px",
      lg: "0 140px",
      xl: "0 140px",
    },
  },
  ContentHeading: {
    fontSize: FONT_SIZE.heading24,
    lineHeight: "32px",
    fontWeight: FONT_WEIGHT.SEMI_BOLD,
    color: commonColor.white,
    textTransform: "uppercase",
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
    marginBottom: "24px",
  },
  ContentText: {
    fontSize: FONT_SIZE.text18,
    lineHeight: "32px",
    fontWeight: FONT_WEIGHT.REGULAR,
    color: commonColor.grey,
    textAlign: "center",
    transition: "all 0.5s ease-in-out",
  },
  VisionSVGContainer: {
    position: "absolute",
    top: "0",
    left: "0",
    width: "100%",
    height: "100%",
  }
};
