import { commonColor } from "@/values/Colors/CommonColor";
import {
    PRICINGICON1, PRICINGICON2, PRICINGICON3, PRICINGICON4,
    PRICINGICON5, PRICINGICON6, PRICINGICON7, PRICINGICON8,
    PRICINGICON9, PRICINGICON10, PRICINGICON11, PRICINGICON12,
    PRICINGICON13, PRICINGICON14, PRICINGICON15, PRICINGICON16,
    PRICINGICON17, PRICINGICON18
} from "@/values/Constants/ImageConstants";

export const PricingBoxContent = [
    {
        id: 1,
        title: "Unlimited 360° Captures",
        desc: "ACapture your site as often as needed – no limits",
        img: PRICINGICON1,
        bgColor: commonColor.lime50,
    },
    {
        id: 2,
        title: "AI-Powered Walk Path Mapping",
        desc: "Automatically generates your movement path on each floorplan from 360° footage.",
        img: PRICINGICON2,
        bgColor: commonColor.white,
    },
    {
        id: 3,
        title: "Unlimited Users",
        desc: "Invite your entire team. No per-user charges",
        img: PRICINGICON3,
        bgColor: commonColor.lime100,
    },
    {
        id: 4,
        title: "Visual Tour Navigation",
        desc: "Navigate floor-by-floor and date-by-date using real captured visuals—not simulations.",
        img: PRICINGICON4,
        bgColor: commonColor.white,
    },
    {
        id: 5,
        title: "Pinpointed Site Notes",
        desc: "Tag issues directly in the scene and floorplan—linked with AI and computer vision.",
        img: PRICINGICON5,
        bgColor: commonColor.lime200,
    },
    {
        id: 6,
        title: "Progress Calendar View",
        desc: "Track visual progress floor-wise for every date captured.",
        img: PRICINGICON6,
        bgColor: commonColor.white,
    },
    {
        id: 7,
        title: "Compare Any Two Dates",
        desc: "Instantly view visual difference of the same spot over time.",
        img: PRICINGICON7,
        bgColor: commonColor.lime100,
    },
    {
        id: 8,
        title: "Photo Capture Without Visiting Site",
        desc: "Take high-resolution photos of any location remotely from office or while travelling.",
        img: PRICINGICON8,
        bgColor: commonColor.white,
    },
    {
        id: 9,
        title: "Export Reports to PDF",
        desc: "Share clean, professional reports with stakeholders.",
        img: PRICINGICON9,
        bgColor: commonColor.lime50,
    },
    {
        id: 10,
        title: "Mobile & Desktop Access",
        desc: "Seamlessly operate from site or office on any device.",
        img: PRICINGICON10,
        bgColor: commonColor.white,
    },
    {
        id: 11,
        title: "Data Retention: 6 Months Included",
        desc: "All plans come with 6 months storage. Extend up to 5 years if needed.",
        img: PRICINGICON11,
        bgColor: commonColor.lime200,
    },
    {
        id: 12,
        title: "Interactive Floorplan Viewer",
        desc: "Jump to any floor or section instantly with visual hotspots.",
        img: PRICINGICON12,
        bgColor: commonColor.white,
    },
    {
        id: 13,
        title: "Secure Cloud Access",
        desc: "Fully encrypted, project-specific access control.",
        img: PRICINGICON13,
        bgColor: commonColor.lime50,
    },
    {
        id: 14,
        title: "No Special Hardware Needed ",
        desc: "Just a 360° camera—no drones, no CCTV, no complexity. Seamless integration.",
        img: PRICINGICON14,
        bgColor: commonColor.white,
    },
    {
        id: 15,
        title: "Fast Setup",
        desc: "Start capturing and tracking in less than 30 minutes setup time.",
        img: PRICINGICON15,
        bgColor: commonColor.lime100,
    },
    {
        id: 16,
        title: "QR Code Project Sharing",
        desc: "Share your floorplan securely with a quick QR code.",
        img: PRICINGICON16,
        bgColor: commonColor.white,
    },
    {
        id: 17,
        title: "One-Click Share for Consultants",
        desc: "Share any floor or section instantly during virtual site visits or meetings.",
        img: PRICINGICON17,
        bgColor: commonColor.lime200,
    },
    {
        id: 18,
        title: "Global Compatibility",
        desc: "Built to serve projects of all sizes across the globe—no restrictions.",
        img: PRICINGICON18,
        bgColor: commonColor.white,
    },
];