import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header/Header";

const Fellix = localFont({
  src: "./fonts/Fellix-Thin.ttf",
  variable: "--font-Fellix-sans",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Fellix.variable}`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}