import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";

export const MUIStyle = {
  HeaderMain: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    background: commonColor.trans,
    width: "100%",
    position: "absolute",
    top: "0",
    left: "0",
    padding: "26px 0",
    zIndex: "999",
    // borderBottom: "1px solid",
  },

  HeaderInner: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: "0px 10px",
    gap: {
      xs: "10px",
      sm: "20px",
    },
  },
  HeaderNavBox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "20px",
    flexDirection: {
      xs: "column",
      sm: "row",
    },
  },
  HeaderLogoBox: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  logoImage: {
    width: {
      xs: "96px",
      sm: "96px",
      md: "120px",
      lg: "120px",
      xl: "120px",
    },
  },

  HeaderBtn: {
    background: commonColor.green,
    border: "2px solid",
    borderColor: commonColor.green,
    boxShadow: "none",
    padding: "7px 42px",
    borderRadius: "100px",
    textTransform: "capitalize",
    fontSize: {
      xs: FONT_SIZE.text16,
      sm: FONT_SIZE.text16,
      md: FONT_SIZE.text16,
      lg: FONT_SIZE.text16,
    },
    lineHeight: "1.8",
    fontWeight: FONT_WEIGHT.MEDIUM,
    color: commonColor.black,
    "&:hover": {
      background: commonColor.trans,
      boxShadow: "none",
      color: commonColor.black,
    },
  },

  MAinMenuBox: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: {
      xs: "stretch",
      sm: "stretch",
      md: "stretch",
      lg: "center",
      xl: "center",
    },
    gap: {
      xs: "10px",
      sm: "20px",
      md: "50px",
      lg: "50px",
      xl: "80px",
    },
    flexDirection: {
      xs: "column",
      sm: "row",
      md: "row",
      lg: "row",
      xl: "row",
    },
  },

  HeaderMenuBox: {
    position: {
      xs: "fixed",
      sm: "fixed",
      md: "relative",
      lg: "relative",
      xl: "relative",
    },
    transition: "all 0.5s",
    background: commonColor.trans,
    top: "0",
    width: "100%",
    height: {
      xs: "100vh",
      sm: "100vh",
      md: "auto",
      lg: "auto",
    },
    padding: {
      xs: "0px",
      sm: "0px",
    },
    zIndex: "999",
    backgroundColor: "#ffffff55 !important",
    borderRadius: '10px',
    boxShadow: '0px 5px 10px rgba(129, 129, 129, 0.5)',
    backdropFilter: 'blur(5px)',
    "&:after": {
      content: '""',
      position: "absolute",
      top: "0",
      left: "0",
      width: "100%",
      height: "100%",
      background: "rgb(0 0 0 / 86%)",
      zIndex: "-1",
      display: {
        xs: "block",
        sm: "block",
        md: "none",
        lg: "none",
      },
    },
  },
  HeadermobInner: {
    width: {
      xs: "87%",
      sm: "60%",
      md: "auto",
      lg: "auto",
    },
    background: {
      xs: commonColor.black,
      sm: commonColor.black,
      md: commonColor.trans,
      lg: commonColor.trans,
      xl: commonColor.trans,
    },
    height: "100%",
    marginLeft: {
      xs: "auto",
      sm: "auto",
      md: "auto",
      lg: "auto",
    },
  },

  menuCloseBtn: {
    height: "40px",
    width: "40px",
    display: {
      xs: "flex",
      sm: "flex",
      md: "none",
      lg: "none",
    },
    justifyContent: "center",
    alignItems: "center",
    fontSize: "30px",
    color: commonColor.yellow,
    background: commonColor.white,
    position: "absolute",
    top: "10px",
    left: {
      xs: "10px",
      sm: "34%",
      md: "auto",
      lg: "auto",
    },
    borderRadius: "50% 50% 0% 50%",
  },
  HeaderMobLogoBox: {
    padding: "20px",
    display: {
      xs: "flex",
      sm: "flex",
      md: "none",
      lg: "none",
    },
  },
  menuBtn: {
    display: {
      xs: "flex",
      sm: "flex",
      md: "none",
      lg: "none",
    },
    justifyContent: "flex-end",
    alignItems: "center",
    fontSize: "30px",
    color: commonColor.lime,
  },
  LogoImgMob: {
    width: {
      xs: "130px",
    },
  },
  HEaderMenu: {
    display: "flex",
    justifyContent: "center",
    flexDirection: {
      xs: "column",
      sm: "column",
      md: "row",
      lg: "row",
    },
    alignItems: {
      xs: "start",
      sm: "start",
      lg: "center",
    },
    gap: {
      xs: "10px",
      sm: "10px",
      md: "10px",
      lg: "10px",
    },
    listStyle: "none",
    padding: "0",
    margin: 0,
    background: commonColor.trans,
  },
  HEaderMenuLi: {
    display: {
      xs: "block",
      sm: "block",
      md: "inline-block",
      lg: "inline-block",
    },
    padding: "0",
    width: {
      xs: "100%",
      sm: "auto",
      md: "auto",
    },
  },
  HeaderMenuBtn: {
    fontSize: FONT_SIZE.text16,
    fontWeight: FONT_WEIGHT.MEDIUM,
    cursor: "pointer",
    padding: "15px 16px",
    transition: "all 0.3s",
    "&:hover": {
      color: commonColor.white,
      boxShadow: "none",
      background: 'linear-gradient(180deg, #030712b0 0%, #03071269 50%, rgba(255, 255, 255, 0) 100%)',
      transition: "all 0.3s",
    },
  },
};
