import { commonColor } from "@/values/Colors/CommonColor";
import { FONT_FAMILY, FONT_SIZE, FONT_WEIGHT } from "@/values/Constants/FontConstants";
import zIndex from "@mui/material/styles/zIndex";

export const MUIStyle = {
    FooterSec: {
        background: commonColor.black,
        width: "100%",
        paddingTop: {
            xs: "40px",
            sm: "40px",
            md: "100px",
            lg: "132px",
            xl: "132px",
        },
        position: "relative",
        overflow: "hidden",
    },
    ftrwaternark: {
        position: "absolute",
        bottom: {
            xs: "-1.5rem",
            sm: "-1.5rem",
            md: "-3.5rem",
            lg: "-3.5rem",
            xl: "-3.5rem",
        },
        left: "50%",
        transform: "translateX(-50%)",
        width: "95%",
        objectFit: "contain",
        zIndex: "0",
    },
    SocialMediaBox: {
        display: "flex",
        gap: "10px",
        alignItems: "center",
    },
    FooterSocialButton:{
        minWidth: "35px",
       fontSize: FONT_SIZE.heading32,
        padding: "0",
        color: commonColor.white,
        "&:hover": {
            color: commonColor.green,
        },
    },
    FooterSocialBox: {
        display: "flex",
        gap: "20px",
        alignItems: "center",
        justifyContent: "start",
    },
    SocialMediaIcon: {
        fontSize: {
            xs: FONT_SIZE.text16,
            sm: FONT_SIZE.text16,
            md: FONT_SIZE.text20,
            lg: FONT_SIZE.text20,
            xl: FONT_SIZE.text20,
        },
        color: commonColor.white,
    },
    FooterRow: {
        display: "flex",
        justifyContent: "space-between",
        flexDirection: {
            xs: "column",
            sm: "column",
            md: "row",
            lg: "row",
            xl: "row",
        },
        alignItems:{
            xs: "center",
            sm: "center",
            md: "flex-start",
            lg: "flex-start",
            xl: "flex-start",
        },
        gap: "50px",
        paddingBottom: {
            xs: "30px",
            sm: "30px",
            md: "100px",
            lg: "132px",
            xl: "132px",
        },
    },
    FooterLogoBox: {
        display: "flex",
        flexDirection: "column",
        alignItems:{
            xs: "center",
            sm: "center",
            md: "flex-start",
            lg: "flex-start",
            xl: "flex-start",
        },
        gap: "24px",
        width: {
            xs: "100%",
            sm: "100%",
            md: "40%",
            lg: "40%",
            xl: "40%",
        },
        "& img": {
            width: "163px",
        },

    },
    FooterMenuBoxOuter:{
        display: "flex",
        justifyContent: {
            xs: "center",
            sm: "center",
            md: "flex-end",
            lg: "flex-end",
            xl: "flex-end",
        },
        flexDirection: {
            xs: "column",
            sm: "column",
            md: "row",
            lg: "row",
            xl: "row",
        },
        alignItems:{
            xs: "center",
            sm: "center",
            md: "flex-end",
            lg: "flex-end",
            xl: "flex-end",
        },
        gap: {
            xs: "20px",
            sm: "20px",
            md: "55px",
            lg: "55px",
            xl: "55px",
        },
        width: "100%",
    },
    FooterLogoText: {
        fontSize: {
            xs: FONT_SIZE.text16,
            sm: FONT_SIZE.text16,
            md: FONT_SIZE.text18,
            lg: FONT_SIZE.text18,
            xl: FONT_SIZE.text18,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.grey,
        lineHeight: "26px",
        textAlign: {
            xs: "center",
            sm: "center",
            md: "left",
            lg: "left",
            xl: "left",
    },
    },
    FooterMenuBox: {
        display: "flex",
        flexDirection: "column",
        gap: {
            xs: "10px",
            sm: "10px",
            md: "20px",
            lg: "20px",
            xl: "20px",
        },
       width: {
            xs: "100%",
            sm: "100%",
            md: "20%",
            lg: "20%",
            xl: "20%",
        },
    },
  
    FooterCunnectMenuLi: {
        display: "grid",
        gap: "15px",
        gridTemplateColumns: "40px 1fr",
        alignItems: "center",
    },
    FooterMenuTitleText: {
        fontSize: {
            xs: FONT_SIZE.text22,
            sm: FONT_SIZE.text22,
            md: FONT_SIZE.heading24,
            lg: FONT_SIZE.heading24,
            xl: FONT_SIZE.heading24,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.white,
        lineHeight: "150%",
        textAlign: {
            xs: "center",
            sm: "center",
            md: "left",
            lg: "left",
            xl: "left",
    },
    },
    FooterMenuUl: {
        display: "flex",
        flexDirection: "column",
        gap: "16px",
        
    },
    FooterMenuLi: {
        display: "flex",
        gap: "10px",
        width: "100%",
        justifyContent: {
            xs: "center",
            sm: "center",
            md: "flex-start",
            lg: "flex-start",
            xl: "flex-start",
        },
        alignItems: "center",
    },
    FooterMenuText: {
        fontSize: {
            xs: FONT_SIZE.text18,
            sm: FONT_SIZE.text18,
            md: FONT_SIZE.text20,
            lg: FONT_SIZE.text20,
            xl: FONT_SIZE.text20,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.grey,
        textAlign: {
            xs: "center",
            sm: "center",
            md: "left",
            lg: "left",
            xl: "left",
    },
        transition: "all 0.4s ease-in-out",
        "&:hover": {
            color: commonColor.green,
            paddingLeft: "10px",
        },
    },
    FooterCunnectIConBox: {
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        fontSize: FONT_SIZE.text20,
        width: "40px",
        height: "40px",
        background: "",
        background: "#14201C",
        borderRadius: "50%",
        color: commonColor.MGoldPrimary,
    },
    FooterMenuNewsBox: {
        display: "flex",
        flexDirection: "column",
        gap: "28px",
        width: {
            xs: "100%",
            sm: "100%",
            md: "25%",
            lg: "25%",
            xl: "25%",
        },
    },


    FooterCopyRightRow : {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        flexDirection: {
            xs: "column",
            sm: "column",
            md: "row",
            lg: "row",
            xl: "row",
        },
        gap: "20px",
        width: "100%",
        padding: "20px 0",
        position: "relative",
        zIndex  : "1",
    },
    FooterCopyRightText : {
        fontSize: {
            xs: FONT_SIZE.text14,
            sm: FONT_SIZE.text14,
            md: FONT_SIZE.text16,
            lg: FONT_SIZE.text16,
            xl: FONT_SIZE.text16,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.grey,
        lineHeight: "24px",
        width: "100%",
        textAlign: {
            xs: "center",
            sm: "center",
            md: "left",
            lg: "left",
            xl: "left",
    },
    },
    FooterPolicyBox : {
        display: "flex",
        gap:{
            xs: "5px",
            sm: "5px",
            md: "20px",
            lg: "20px",
            xl: "20px",
        },
        alignItems: "center",
        justifyContent:{
            xs: "center",
            sm: "center",
            md: "flex-end",
            lg: "flex-end",
            xl: "flex-end",
        },
        width: "100%",
    },
    FooterPolicyText : {
        fontSize: {
            xs: FONT_SIZE.text12,
            sm: FONT_SIZE.text14,
            md: FONT_SIZE.text16,
            lg: FONT_SIZE.text16,
            xl: FONT_SIZE.text16,
        },
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.grey,
        lineHeight: "24px",
    },
    FooterPolicyDivider : {
        fontSize: FONT_SIZE.text16,
        fontWeight: FONT_WEIGHT.MEDIUM,
        color: commonColor.grey,
        lineHeight: "24px",
    },



};
